name: Darragh Martin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06514801806770265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ceedff'
    - '#6b573c'
    - '#978263'
    - '#382514'
    - '#abbabf'
  brandStrength: 0.5
  lightness: 0.7690869574435055
  saturation: 0.5325482657644898
  rhythmicContrast: 0.033939983462914824
purpose: []
