name: Darragh Martin
favicon: null
layout_spectrum: 0.10938227642327547
typography_spectrum: 0.06514801806770265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5001596109941602
  lightness: 0.7690869574435055
  saturation: 0.5325482657644898
  rhythmicContrast: 0.033939983462914824
purpose: []
